### ISSUE TITLE
Heap-buffer-overflow in rleUncompress at tinyexr.h:7712

### ISSUE THREAD

**Issue by Kondara** [syoyo/tinyexr#112]
Project was cloned today and compiled with g++ using the following options:

> -g -O1 -fsanitize=address,undefined -lz

This specific test case can be found at: https://github.com/Kondara/Testcases/blob/master/crash1.exr

```
jonathan@kondara:~/tinyexr2$ ./tinyexr-parse-asan crash1.exr
=================================================================
==3754==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61c000000fe4 at pc 0x56189780c2fa bp 0x7ffcb0871240 sp 0x7ffcb0871230
READ of size 1 at 0x61c000000fe4 thread T0
    #0 0x56189780c2f9 in rleUncompress /home/jonathan/tinyexr2/tinyexr.h:7712
    #1 0x56189780c2f9 in DecompressRle /home/jonathan/tinyexr2/tinyexr.h:7809
    #2 0x56189780c2f9 in DecodePixelData /home/jonathan/tinyexr2/tinyexr.h:9922
    #3 0x56189785b0c1 in DecodeChunk /home/jonathan/tinyexr2/tinyexr.h:10959
    #4 0x56189785f051 in DecodeEXRImage /home/jonathan/tinyexr2/tinyexr.h:11165
    #5 0x56189785f051 in LoadEXRImageFromMemory /home/jonathan/tinyexr2/tinyexr.h:11698
    #6 0x561897860f92 in LoadEXRImageFromFile /home/jonathan/tinyexr2/tinyexr.h:11675
    #7 0x5618978769aa in LoadEXR /home/jonathan/tinyexr2/tinyexr.h:11235
    #8 0x561897879320 in main /home/jonathan/tinyexr2/tinyexr-parse.cpp:18
    #9 0x7f57d3d75b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #10 0x5618977dc329 in _start (/home/jonathan/tinyexr2/tinyexr-parse-asan+0x10a329)

0x61c000000fe4 is located 0 bytes to the right of 1892-byte region [0x61c000000880,0x61c000000fe4)
allocated by thread T0 here:
    #0 0x7f57d54e7458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x56189785fa27 in __gnu_cxx::new_allocator<unsigned char>::allocate(unsigned long, void const*) /usr/include/c++/7/ext/new_allocator.h:111
    #2 0x56189785fa27 in std::allocator_traits<std::allocator<unsigned char> >::allocate(std::allocator<unsigned char>&, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:436
    #3 0x56189785fa27 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_allocate(unsigned long) /usr/include/c++/7/bits/stl_vector.h:172
    #4 0x56189785fa27 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_create_storage(unsigned long) /usr/include/c++/7/bits/stl_vector.h:187
    #5 0x56189785fa27 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_base(unsigned long, std::allocator<unsigned char> const&) /usr/include/c++/7/bits/stl_vector.h:138
    #6 0x56189785fa27 in std::vector<unsigned char, std::allocator<unsigned char> >::vector(unsigned long, std::allocator<unsigned char> const&) /usr/include/c++/7/bits/stl_vector.h:284
    #7 0x56189785fa27 in LoadEXRImageFromFile /home/jonathan/tinyexr2/tinyexr.h:11665
    #8 0x5618978769aa in LoadEXR /home/jonathan/tinyexr2/tinyexr.h:11235
    #9 0x561897879320 in main /home/jonathan/tinyexr2/tinyexr-parse.cpp:18
    #10 0x5618978ce307  (/home/jonathan/tinyexr2/tinyexr-parse-asan+0x1fc307)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/jonathan/tinyexr2/tinyexr.h:7712 in rleUncompress
Shadow bytes around the buggy address:
  0x0c387fff81a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff81b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff81c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff81d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff81e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c387fff81f0: 00 00 00 00 00 00 00 00 00 00 00 00[04]fa fa fa
  0x0c387fff8200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c387fff8210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c387fff8220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c387fff8230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c387fff8240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3754==ABORTING
```

**Comment by syoyo** [comment]
`rleUncompress` is grabbed from OpenEXR source code and currently we don't know how to fix it.

@Kondara You can send PR though!

**Comment by Kondara** [comment]
@syoyo First off, thanks for your swift action and comments on these types of issues, it is much appreciated. 

After taking a quick glance at it, the issue starts pretty early (likely even earlier) when `DecodePixelData` calls `DecompressRle` with a src_size of 1. From my understanding of RLE, it expects pairs (count and value) of data so sending an odd data length to decompression will cause this issue every time. `rleUncompress` will increment the incoming data buffer and use it in either the memcpy or memset depending on the path taken causing the out of bounds access.

I'd suggest possibly making a data length check (length divisible by 2 possibly?) in `DecodePixelData` when we know the decompression type is `TINYEXR_COMPRESSIONTYPE_RLE` before making the call to `tinyexr::DecompressRle`.

**Comment by syoyo** [comment]
Thank you for investing an issue.

> I'd suggest possibly making a data length check (length divisible by 2 possibly?)

I have added workaround of checking src buffer size is larger than 2 in this commit:

https://github.com/syoyo/tinyexr/commit/58a625894cfbb76da1d599e4f9768f099058e0e4

At least https://github.com/Kondara/Testcases/blob/master/crash1.exr now passes.


I'm not sure its always safe to add the check of `src length is dividable by 2`. We need more investigation.

**Comment by Kondara** [comment]
My concern is any odd number (1, 3, 5, etc) length sent to `DecompressRle` will cause this out of bound access. I'll see if I can modify the test case to demonstrate, if not fuzzing should catch it.

Happy to consider this closed and if I am able to demonstrate the concern I will file a new issue.

Cheers!
