### ISSUE TITLE
Heap-buffer-overflow in rleUncompress at tinyexr.h:7721

### ISSUE THREAD

**Issue by Kondara** [syoyo/tinyexr#116]
Project was cloned today and compiled with g++ using the following options:

>-g -O1 -fsanitize=address,undefined -lz

This specific test case can be found at: https://github.com/Kondara/Testcases/blob/master/crash3.exr

The cause of this issue is that while `rleUncompress` checks to make sure we don't write past the bounds of the `out` buffer, it fails to check if we read past the bounds of the `in` buffer before calling `memcpy`.

Since the RLE code was taken from the OpenEXR project and it looks to be unchanged there I will submit a PR for review soon.

```
++++++++++++++++++++++++++++++++++++++++++++++++++
+ Entering rleUncompress                         +
++++++++++++++++++++++++++++++++++++++++++++++++++
inLength  = 100
maxLength = 33292388
in        = 0x61d0000011e3
out       = 0x7f2093e38800
----------------------Loop------------------------
inLength  = 100
*in       = 0
...
----------------------Loop------------------------
inLength  = 16
*in       = -76
Taking true route [ if (*in < 0) ]
count     = 76
inLength  = -61 (updated) // inLength -= count + 1;
in        = 0x61d000001238
maxLength = 33292346
// OOB here on memcpy
// memcpy(out, in, count);
```

```
jonathan@kondara:~/tinyexr$ ./tinyexr-parse-asan crash3.exr
=================================================================
==3505==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d000001248 at pc 0x7f48b6a39733 bp 0x7ffc08601850 sp 0x7ffc08600ff8
READ of size 76 at 0x61d000001248 thread T0
    #0 0x7f48b6a39732  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732)
    #1 0x56271725a3b7 in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
    #2 0x56271725a3b7 in rleUncompress /home/jonathan/tinyexr/tinyexr.h:7705
    #3 0x56271725a3b7 in DecompressRle /home/jonathan/tinyexr/tinyexr.h:7817
    #4 0x56271725a3b7 in DecodePixelData /home/jonathan/tinyexr/tinyexr.h:9936
    #5 0x5627172a9347 in DecodeChunk /home/jonathan/tinyexr/tinyexr.h:10982
    #6 0x5627172ad30e in DecodeEXRImage /home/jonathan/tinyexr/tinyexr.h:11188
    #7 0x5627172ad30e in LoadEXRImageFromMemory /home/jonathan/tinyexr/tinyexr.h:11721
    #8 0x5627172af24f in LoadEXRImageFromFile /home/jonathan/tinyexr/tinyexr.h:11698
    #9 0x5627172c4c67 in LoadEXR /home/jonathan/tinyexr/tinyexr.h:11258
    #10 0x5627172c75dd in main /home/jonathan/tinyexr/tinyexr-parse.cpp:18
    #11 0x7f48b532eb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #12 0x56271722a3d9 in _start (/home/jonathan/tinyexr/tinyexr-parse-asan+0x10a3d9)

0x61d000001248 is located 0 bytes to the right of 1992-byte region [0x61d000000a80,0x61d000001248)
allocated by thread T0 here:
    #0 0x7f48b6aa0458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x5627172adce4 in __gnu_cxx::new_allocator<unsigned char>::allocate(unsigned long, void const*) /usr/include/c++/7/ext/new_allocator.h:111
    #2 0x5627172adce4 in std::allocator_traits<std::allocator<unsigned char> >::allocate(std::allocator<unsigned char>&, unsigned long) /usr/include/c++/7/bits/alloc_traits.h:436
    #3 0x5627172adce4 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_allocate(unsigned long) /usr/include/c++/7/bits/stl_vector.h:172
    #4 0x5627172adce4 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_create_storage(unsigned long) /usr/include/c++/7/bits/stl_vector.h:187
    #5 0x5627172adce4 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_base(unsigned long, std::allocator<unsigned char> const&) /usr/include/c++/7/bits/stl_vector.h:138
    #6 0x5627172adce4 in std::vector<unsigned char, std::allocator<unsigned char> >::vector(unsigned long, std::allocator<unsigned char> const&) /usr/include/c++/7/bits/stl_vector.h:284
    #7 0x5627172adce4 in LoadEXRImageFromFile /home/jonathan/tinyexr/tinyexr.h:11688
    #8 0x5627172c4c67 in LoadEXR /home/jonathan/tinyexr/tinyexr.h:11258
    #9 0x5627172c75dd in main /home/jonathan/tinyexr/tinyexr-parse.cpp:18
    #10 0x56271731c5f7  (/home/jonathan/tinyexr/tinyexr-parse-asan+0x1fc5f7)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x79732)
Shadow bytes around the buggy address:
  0x0c3a7fff81f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a7fff8200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a7fff8210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a7fff8220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a7fff8230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3a7fff8240: 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa
  0x0c3a7fff8250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a7fff8260: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a7fff8270: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a7fff8280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a7fff8290: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3505==ABORTING
```

**Comment by syoyo** [comment]
Thanks for the investigation. PR has been merged and I've confirmed now it goes OK. 

@Kondara Please close the issue once you also confirmed the issue has been solved on your side.
