### ISSUE TITLE
PIZ compression bug

### ISSUE THREAD

**Issue by pgrit** [syoyo/tinyexr#160]
I found a weird bug where reading an image with PIZ compression can cause artifacts, where line(s) of pixels that should be black instead have every second pixel's red channel set to a very high value.
![bug](https://user-images.githubusercontent.com/12607894/126062834-462a602b-6655-4ae7-af35-21964e953084.png)

This only happens with PIZ compression, none of the others. It does not happen with all images. The position of the red lines depends on the image. But it is deterministic, so threading issues are unlikely. If there are multiple such lines, the distance between them is exactly 32 pixels.

The problem is tied to specific files, the dots appear when reading the PIZ compressed file. Reading the same file with OpenEXR does not produce the red dots.

**To Reproduce**

1. Load EXR Image from the .zip below
2. There will not be any red dots
3. Save EXR again, as `test.exr`, making sure to use `TINYEXR_COMPRESSIONTYPE_PIZ`
4. [optional] Read the new `test.exr` with OpenEXR - there will not be any red dots
5. Read the new `test.exr` with tinyexr - the red dots appear
6. [optional] Save again, the dots will now be visible in any viewer that uses OpenEXR

[RedDotsTest.zip](https://github.com/syoyo/tinyexr/files/6835972/RedDotsTest.zip)

**Environment**
 - OS: Windows, Ubuntu
 - Compiler: latest VS, gcc 9
 - OpenMP enabled

**Comment by syoyo** [comment]
Uncomment `SIMPLE_API_EXAMPLE`  and change compression to PIZ in `test_tinyexr`, read/convert RedDotsTest.exr and open `output_test.exr` in exrviewer does not show any artifact.

You need to provide minimal reproducible code.

```
$ file output_test.exr 
output_test.exr: OpenEXR image data, version 2, storage: scanline, compression: piz, dataWindow: (0 0)-(639 479), displayWindow: (0 0)-(639 479), lineOrder: increasing y
```
![Screenshot from 2021-07-18 19-34-38](https://user-images.githubusercontent.com/18676/126064078-20184b1f-63c0-4af7-a2ab-e260ffaa98ed.png)

**Comment by pgrit** [comment]
Not sure what your "exrviewer" is, if that is not using tinyexr than it will not yet show the problem. 

Not quite "minimal" but I boiled it down to a single C++ file with my loading / writing code: [TinyExrPIZ.zip](https://github.com/syoyo/tinyexr/files/6836522/TinyExrPIZ.zip)

You can compile and run via something along the lines of: (depends on OS, of course)

```
mkdir build && cd build && cmake .. && cmake --build . && ./TinyExrPIZ
```

The output will be:
```
(639, 479).R = 0
(639, 479).R = 6.69209e+21
```

Expected output, e.g., if you change lines 167-169 in main.cpp to use ZIP instead of PIZ:
```
(639, 479).R = 0
(639, 479).R = 0
```

And the key procedure, if you'd rather reproduce it with your own loading / writing code is:
```C++
int main() {
    // Read the original image
    int width = 640, height = 480, numChannels = 4;
    int idx = CacheExrImage("../original.exr");
    float* data = new float[width * height * numChannels];
    CopyCachedExrLayer(idx, "default", data);

    std::cout << "(639, 479).R = " << data[479 * width * numChannels + 639 * numChannels] << std::endl;

    // Save under a new name with PIZ compression
    int rowStride = numChannels * width;
    WriteImageToExr(&data, &rowStride, width, height, &numChannels, 1, nullptr, "../test.exr");

    // Read the new image file
    idx = CacheExrImage("../test.exr");
    CopyCachedExrLayer(idx, "default", data);

    std::cout << "(639, 479).R = " << data[479 * width * numChannels + 639 * numChannels] << std::endl;

    // Save again, red dots will only appear in this new "test2.exr"
    WriteImageToExr(&data, &rowStride, width, height, &numChannels, 1, nullptr, "../test2.exr");

    return 0;
}
```

When I view the images with tev (which uses OpenEXR), then only `test2.exr` will have a row of red dots in the bottom right.

**Comment by syoyo** [comment]
@pgrit Thanks! I can reproduce it(macOS apple clang). 

When I dump the pixel value after the decode,

```
...
val = 3.57681e-41
val = 6.67772e+21
val = 0
val = 6.69209e+21
val = 0
val = 6.69209e+21
val = 0
val = 6.69209e+21
...
```

It has too small and too large fp value.

The issue will be within PIZ compression or decompression. But finding the reason is difficult since the code is ported from rather old OpenEXR and add TinyEXR adds some fixes. The solution may be port PIZ compress/decompress routine from recent OpenEXR but it is a time-consuming task.

So, workaround so far is not to use PIZ compression 😃 

FYI OpenMP was not related to the issue. 

`exrviewer` : Ah, I meant exrdisplay program in OpenEXR package https://www.openexr.com/using.html

**Comment by syoyo** [comment]
@pgrit FYI the issue seems exit in PIZ decode. 

Decode attached PIZ compressed EXR in OpenEXR viewer(e.g. macOS Finder) : No issue
Decode attached PIZ compressed EXR in tinyexr and save it as NO_COMPRESSION: Has white-dot artifacts(in the last line of image)
<img width="578" alt="Screen Shot 2021-07-23 at 2 20 05" src="https://user-images.githubusercontent.com/18676/126681641-7bb8d6f1-a53d-4f95-922f-8466696bf956.png">

[piztest.exr.zip](https://github.com/syoyo/tinyexr/files/6864081/piztest.exr.zip)

**Comment by pgrit** [comment]
I made a little Python script to generate images that produce the problem.

This seems to only happen if the image contains noisy data, and has a solid-color or black region on the right that is at least 60 pixels wide.

The lines are always in a scanline that is a multiple of 32 when counting from the top, i.e., the last of `num_scanline_blocks` for the PIZ encoding.

If I put a red pixel right next to where such an artifact dot would appear, the whole line goes away.

```python
import OpenEXR
import Imath
import numpy as np
import simpleimageio as sio

width = 420
height = 32
border_left = 0
border_right = 420 - 80
num_splats = 10000

red = np.zeros((height, width), dtype=np.float32)
green = np.zeros((height, width), dtype=np.float32)
blue = np.zeros((height, width), dtype=np.float32)

# splat random color values
rng = np.random.default_rng()
row = rng.integers(low=0, high=height, size=num_splats)
col = rng.integers(low=border_left, high=border_right, size=num_splats)

# if any of the three channels has a fixed value, the problem goes away!
red[row, col] = rng.random(num_splats)
green[row, col] = rng.random(num_splats)
blue[row, col] = rng.random(num_splats)

# add a bunch of test pixels
red[-8, -10] = 1
green[-8, -10] = 1
blue[-8, -10] = 1

red[-4, -8] = 1
green[-4, -8] = 1
blue[-4, -8] = 1

red[-4, -2] = 1
green[-4, -2] = 1
blue[-4, -2] = 1

red[-2, -3] = 0 # setting this to anything other than 0 fixes the problem
green[-2, -3] = 1
blue[-2, -3] = 1

# fill in all of the black region with 0-red color
# red[:,border_right:] = 0
# green[:,border_right:] = 1
# blue[:,border_right:] = 1

# write PIZ compressed via OpenEXR
header = OpenEXR.Header(width, height)
header['compression'] = Imath.Compression(Imath.Compression.PIZ_COMPRESSION)
exr = OpenEXR.OutputFile("gen.exr", header)
exr.writePixels({'R': red.tobytes(), 'G': green.tobytes(), 'B': blue.tobytes()})
exr.close()

# read back in via tinyexr (used internally by simpleimageio)
tinyresult = sio.read("gen.exr")
sio.write("test2.exr", tinyresult)
```

![image](https://user-images.githubusercontent.com/12607894/126698366-0f226b57-e81b-4151-b49e-8b8b1318ec7f.png)

**Comment by syoyo** [comment]
@pgrit Thanks! After debugging TinyEXR and OpenEXR(recent `main` branch). I found the issue was in OpenEXR.

Your data triggers out-of-bounds access in OpenEXR when compiled with AddressSanitizer.

```
==315369==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f1a14d5de00 at pc 0x7f1a1826996b bp 0x7fff2f4a9510 sp 0x7fff2f4a9508
READ of size 2 at 0x7f1a14d5de00 thread T0
    #0 0x7f1a1826996a in Imf_3_1::(anonymous namespace)::hufDecode(unsigned long const*, Imf_3_1::(anonymous namespace)::HufDec const*, char const*, int, int, int, unsigned short*) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfHuf.cpp:923:52
    #1 0x7f1a1826996a in Imf_3_1::hufUncompress(char const*, int, unsigned short*, int) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfHuf.cpp:1132:13
    #2 0x7f1a182fd8f0 in Imf_3_1::PizCompressor::uncompress(char const*, int, Imath_3_2::Box<Imath_3_2::Vec2<int> >, char const*&) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfPizCompressor.cpp:582:5
    #3 0x7f1a182fc704 in Imf_3_1::PizCompressor::uncompress(char const*, int, int, char const*&) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfPizCompressor.cpp:258:12
    #4 0x7f1a1833d4de in Imf_3_1::(anonymous namespace)::LineBufferTask::execute() /home/syoyo/work/openexr/src/lib/OpenEXR/ImfScanLineInputFile.cpp:527:66
    #5 0x7f1a17f0535e in IlmThread_3_1::(anonymous namespace)::NullThreadPoolProvider::addTask(IlmThread_3_1::Task*) /home/syoyo/work/openexr/src/lib/IlmThread/IlmThreadPool.cpp:399:12
    #6 0x7f1a17f05241 in IlmThread_3_1::ThreadPool::addTask(IlmThread_3_1::Task*) /home/syoyo/work/openexr/src/lib/IlmThread/IlmThreadPool.cpp:752:28
    #7 0x7f1a17f05241 in IlmThread_3_1::ThreadPool::addGlobalTask(IlmThread_3_1::Task*) /home/syoyo/work/openexr/src/lib/IlmThread/IlmThreadPool.cpp:776:24
    #8 0x7f1a1832f925 in Imf_3_1::ScanLineInputFile::readPixels(int, int) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfScanLineInputFile.cpp:1691:17
    #9 0x7f1a18298a5f in Imf_3_1::InputFile::readPixels(int, int) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfInputFile.cpp:914:23
    #10 0x7f1a18681e8e in bool Imf_3_1::(anonymous namespace)::readScanline<Imf_3_1::InputPart>(Imf_3_1::InputPart&, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:203:19
    #11 0x7f1a18681e8e in Imf_3_1::(anonymous namespace)::readMultiPart(Imf_3_1::MultiPartInputFile&, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:801:28
    #12 0x7f1a1867e456 in bool Imf_3_1::(anonymous namespace)::runChecks<char const*>(char const*&, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:1050:18
    #13 0x7f1a1867e456 in Imf_3_1::checkOpenEXRFile(char const*, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:1165:11
    #14 0x4cc38a in exrCheck(char const*, bool, bool, bool) /home/syoyo/work/openexr/src/bin/exrcheck/main.cpp:65:14
    #15 0x4ccd6f in main /home/syoyo/work/openexr/src/bin/exrcheck/main.cpp:129:29
    #16 0x7f1a17a160b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #17 0x41d45d in _start (/home/syoyo/work/openexr/build/bin/exrcheck+0x41d45d)

0x7f1a14d5de00 is located 0 bytes to the right of 161280-byte region [0x7f1a14d36800,0x7f1a14d5de00)
allocated by thread T0 here:
    #0 0x4c98dd in operator new[](unsigned long) /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:102:3
    #1 0x7f1a182f8a96 in Imf_3_1::PizCompressor::PizCompressor(Imf_3_1::Header const&, unsigned long, unsigned long) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfPizCompressor.cpp:167:18
    #2 0x7f1a1817d385 in Imf_3_1::newCompressor(Imf_3_1::Compression, unsigned long, Imf_3_1::Header const&) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfCompressor.cpp:132:13
    #3 0x7f1a18329181 in Imf_3_1::ScanLineInputFile::initialize(Imf_3_1::Header const&) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfScanLineInputFile.cpp:1141:53
    #4 0x7f1a18329e1b in Imf_3_1::ScanLineInputFile::ScanLineInputFile(Imf_3_1::InputPartData*) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfScanLineInputFile.cpp:1185:8
    #5 0x7f1a18294121 in Imf_3_1::InputFile::initialize() /home/syoyo/work/openexr/src/lib/OpenEXR/ImfInputFile.cpp:678:32
    #6 0x7f1a18296def in Imf_3_1::InputFile::multiPartInitialize(Imf_3_1::InputPartData*) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfInputFile.cpp:594:5
    #7 0x7f1a18296def in Imf_3_1::InputFile::InputFile(Imf_3_1::InputPartData*) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfInputFile.cpp:557:8
    #8 0x7f1a182d0715 in Imf_3_1::InputFile* Imf_3_1::MultiPartInputFile::getInputPart<Imf_3_1::InputFile>(int) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfMultiPartInputFile.cpp:159:23
    #9 0x7f1a1829dce2 in Imf_3_1::InputPart::InputPart(Imf_3_1::MultiPartInputFile&, int) /home/syoyo/work/openexr/src/lib/OpenEXR/ImfInputPart.cpp:16:26
    #10 0x7f1a18681786 in Imf_3_1::(anonymous namespace)::readMultiPart(Imf_3_1::MultiPartInputFile&, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:800:27
    #11 0x7f1a1867e456 in bool Imf_3_1::(anonymous namespace)::runChecks<char const*>(char const*&, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:1050:18
    #12 0x7f1a1867e456 in Imf_3_1::checkOpenEXRFile(char const*, bool, bool) /home/syoyo/work/openexr/src/lib/OpenEXRUtil/ImfCheckFile.cpp:1165:11
    #13 0x4cc38a in exrCheck(char const*, bool, bool, bool) /home/syoyo/work/openexr/src/bin/exrcheck/main.cpp:65:14
    #14 0x4ccd6f in main /home/syoyo/work/openexr/src/bin/exrcheck/main.cpp:129:29
    #15 0x7f1a17a160b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/syoyo/work/openexr/src/lib/OpenEXR/ImfHuf.cpp:923:52 in Imf_3_1::(anonymous namespace)::hufDecode(unsigned long const*, Imf_3_1::(anonymous namespace)::HufDec const*, char const*, int, int, int, unsigned short*)
Shadow bytes around the buggy address:
  0x0fe3c29a3b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe3c29a3b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe3c29a3b90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe3c29a3ba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe3c29a3bb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe3c29a3bc0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe3c29a3bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe3c29a3be0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe3c29a3bf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe3c29a3c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe3c29a3c10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==315369==ABORTING

```

, which is fixed in TinyEXR

https://github.com/syoyo/tinyexr/blob/7f349394cc7b179b9e43a9a1bd6b3d17dcf7db55/tinyexr.h#L2607

https://github.com/syoyo/tinyexr/issues/78

When I dump decoded Huffman data

https://github.com/AcademySoftwareFoundation/openexr/blob/d8dd06a3fa4e856627a60ecdbd8b8eed0f0b2e8a/src/lib/OpenEXR/ImfPizCompressor.cpp#L573
https://github.com/syoyo/tinyexr/blob/7f349394cc7b179b9e43a9a1bd6b3d17dcf7db55/tinyexr.h#L3120

OpenEXR outputs 

```
hufUncompress[80475] = 37610
hufUncompress[80476] = 35878
hufUncompress[80477] = 35330
hufUncompress[80478] = 43310
hufUncompress[80479] = 37140
hufUncompress[80480] = 32768
hufUncompress[80481] = 32768
hufUncompress[80482] = 32768
hufUncompress[80483] = 32768
hufUncompress[80484] = 32768
...
```

whereas TinyEXR outputs

```
hufUncompress[80475] = 37610
hufUncompress[80476] = 35878
hufUncompress[80477] = 35330
hufUncompress[80478] = 43310
hufUncompress[80479] = 37140
hufUncompress[80480] = 32768
hufUncompress[80481] = 0
hufUncompress[80482] = 0
hufUncompress[80483] = 0
hufUncompress[80484] = 0
...
```

## workaround

Add extra bytes to tmpBuffer would solve the issue. I will create PR soon.

## Recommended solution

OpenEXR should fix this out-of-bounds issue. I will submit an issue to OpenEXR project soon.

**Comment by syoyo** [comment]
@pgrit BTW simpleimageio is nice! You may be interested in https://github.com/syoyo/tinydngloader to support loading/saving 32bit FP TIFF images for simpleimageio

**Comment by pgrit** [comment]
> @pgrit BTW simpleimageio is nice! You may be interested in https://github.com/syoyo/tinydngloader to support loading/saving 32bit FP TIFF images for simpleimageio

Thanks for the link! And nice work! Incorporating it was really quick and easy. Although the saving part is quite well hidden in the repo ;)

**Comment by syoyo** [comment]
@pgrit Writer module is added later so code is not organized well and have less information about it. Added some comments in tinydngloader's README.

**Comment by syoyo** [comment]
PR has been merged! https://github.com/syoyo/tinyexr/pull/161

@pgrit Thank you for reporting the issue & creating reproducible scripts!
